### ISSUE TITLE
Expand test-cases

### ISSUE THREAD

**Issue by Krzmbrzl** [KoffeinFlummi/armake2#33] opened 2019-04-24 05:49 UTC
Thhis kinda goes along with #27 but should go further. Currently the only tests that exist are a single one for config-rapification and a single preprocessor test.

There should also be tests for all other functionality of armake (especially PBO packing).

Also those tests should be run on each Travis/AppVeyor build.

**Comment by KoffeinFlummi** [comment] 2019-05-13 18:12
Too general/duplicate of #27.

**Closed as completed by KoffeinFlummi** 2019-05-13 18:12 UTC
Labels: duplicate
